name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Gradle:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradle executable
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
      - name: Build Release APK
        run: .\gradlew assembleRelease
      - name: Releasing using Hub
        uses: r0user/release-apk@main
        env:
          GITHUB_TOKEN: ${{ secrets.FLAPPYBIRD_TOKEN }}
          APP_FOLDER: app
